from klass import Inimene

inimene1 = Inimene("Timmu", "Õunapuu", 5)
inimene2 = Inimene("Joonatan", "Rõngas", 3)
inimene3 = Inimene("Jaanus", "Toots", 1)
inimene1.tutvustus()
inimene2.tutvustus()
inimene3.tutvustus()
inimene1.getmin()
inimene2.getmin()
inimene3.getmin()
inimene1.suurenda_sisselogimiskatsed()
inimene1.suurenda_sisselogimiskatsed()
inimene1.suurenda_sisselogimiskatsed()
inimene2.suurenda_sisselogimiskatsed()
inimene2.suurenda_sisselogimiskatsed()
inimene3.suurenda_sisselogimiskatsed()
inimene1.reset_sisselogimiskatsed()
inimene2.reset_sisselogimiskatsed()
inimene3.reset_sisselogimiskatsed()
inimene1.maara_parool("apelsin")
inimene1.naita_parool()
inimene2.kontrolli_parool("aa")
inimene2.naita_parool()
inimene2.kontrolli_parool("12345678")
inimene2.naita_parool()
inimene3.kasutajanimi()
inimene3.parool()
input()